import test from 'node:test';import assert from 'node:assert/strict';
// Tutor engine contract: unknown messages still get a real answer, the fallback names the
// lesson concepts, and no draft can leak a ready-made solution or a private reference.
// Regression suite for the 2026-09-15 fix ("the helper does not help").
import {createEngine,approved,textAllowed,buildFallback,CLARIFY_HINT,OUTSIDE,FUTURE} from '../server/engine.mjs';
import {createProvider} from '../server/provider.mjs';
const curriculum={variables:{id:'variables',title:'Переменные',level:'basic',focus:'int, переменная',excluded:'классы',prerequisites:[],theory:[{title:'Тип',text:'Переменная хранит значение'}],exercises:[{id:'task-1',title:'Счётчик',task:'Разберись со счётчиком',reference:'PRIVATE_ANSWER_SENTINEL'}]}};
const pass={approve:true,scope:true,level:true,correctness:true,noSolution:true,cumulativeSafe:true,ageAppropriate:true,reasonCodes:[],feedback:''};
const safe='Переменная хранит значение, а имя помогает к нему обратиться. Представь подписанную коробку: содержимое можно менять, а название остаётся прежним.';
const inside=JSON.stringify({scope:'in',exerciseId:null,solutionRequest:false});
function harness(sequence){const calls=[];return {calls,run:createEngine({curriculum,callModel:async r=>{calls.push(r);const response=sequence.shift();if(response instanceof Error)throw response;if(response===undefined)throw Error('Unexpected call');return response;}})};}
test('approved draft only; private answers not sent to tutor',async()=>{const h=harness([inside,safe,JSON.stringify(pass)]);const result=await h.run({lessonId:'variables',message:'Что такое переменная?'});assert.equal(result.text,safe);assert.equal(result.approved,true);assert.ok(!JSON.stringify(h.calls[1]).includes('PRIVATE_ANSWER_SENTINEL'));assert.ok(JSON.stringify(h.calls[2]).includes('PRIVATE_ANSWER_SENTINEL'));});
test('unrelated and future topics never reach tutor',async()=>{for(const [scope,text] of [['out',OUTSIDE],['future',FUTURE]]){const h=harness([JSON.stringify({scope,exerciseId:null,solutionRequest:false})]);assert.equal((await h.run({lessonId:'variables',message:'other'})).text,text);assert.equal(h.calls.length,1);}});
test('reviewer unavailable blocks draft',async()=>{const h=harness([inside,safe,new Error('provider failure')]);const r=await h.run({lessonId:'variables',message:'вопрос'});assert.equal(r.kind,'unavailable');assert.notEqual(r.text,safe);});
test('malformed approval and all criteria fail closed',()=>{assert.ok(approved(pass));for(const key of Object.keys(pass).filter(k=>typeof pass[k]==='boolean'))assert.ok(!approved({...pass,[key]:false}));assert.ok(!approved({...pass,extra:'x'}));assert.ok(!approved({...pass,approve:'true'}));assert.ok(!approved({...pass,reasonCodes:['solution']}));});
test('rejected draft reaches repair as data, without private reviewer feedback',async()=>{const draft='Перенеси объявление счётчика за пределы функции, тогда оно будет общим. DRAFT_SENTINEL';const h=harness([inside,draft,JSON.stringify({...pass,approve:false,noSolution:false,reasonCodes:['solution'],feedback:'PRIVATE_ANSWER_SENTINEL'}),safe,JSON.stringify(pass)]);const history=[{role:'user',content:'Объясни счётчик'},{role:'assistant',content:'Вспомни область видимости'}];const r=await h.run({lessonId:'variables',message:'реши',exerciseId:'task-1',history});assert.equal(r.text,safe);assert.equal(r.approved,true);assert.equal(h.calls.length,5);const repair=h.calls[3];assert.ok(!JSON.stringify(repair).includes('PRIVATE_ANSWER_SENTINEL'));assert.ok(!repair.messages.filter(m=>m.role==='system').some(m=>m.content.includes('DRAFT_SENTINEL')));const data=JSON.parse(repair.messages.at(-1).content);assert.equal(data.rejectedDraft,draft);assert.equal(data.message,'реши');assert.deepEqual(data.history,history);assert.ok(repair.messages.some(m=>m.role==='system'&&m.content.includes('Убери готовое изменение')));assert.equal(JSON.parse(h.calls[4].messages.at(-1).content).draft,safe);assert.ok(!JSON.stringify(h.calls[4]).includes('DRAFT_SENTINEL'));assert.deepEqual(history,[{role:'user',content:'Объясни счётчик'},{role:'assistant',content:'Вспомни область видимости'}]);});
test('cumulative leakage rejected after one repair without a third draft',async()=>{const reject=JSON.stringify({...pass,approve:false,cumulativeSafe:false,reasonCodes:['cumulative_solution']});const h=harness([inside,safe,reject,safe,reject]);const history=[{role:'user',content:'Сначала дай начало'},{role:'assistant',content:'Предыдущая подсказка'}];const r=await h.run({lessonId:'variables',message:'теперь продолжи',history});assert.equal(r.text,buildFallback(curriculum.variables));assert.equal(r.approved,false);assert.equal(h.calls.length,5);assert.ok(h.calls.filter(c=>c.phase==='review').every(c=>JSON.stringify(c.messages).includes('Предыдущая подсказка')));});
test('format rejection has only one bounded repair and never reaches review',async()=>{const draft='```cpp\n'+('x'.repeat(5000));const h=harness([inside,draft,draft]);const result=await h.run({lessonId:'variables',message:'дай код'});assert.equal(result.text,buildFallback(curriculum.variables));assert.equal(h.calls.length,3);assert.equal(JSON.parse(h.calls[2].messages.at(-1).content).rejectedDraft,draft.slice(0,2200));assert.ok(!h.calls.some(c=>c.phase==='review'));});
test('vague message still gets a real answer instead of a canned prompt',async()=>{for(const message of ['не работает','помогите','не получается с кнопкой','не понимаю, как писать код']){const h=harness([JSON.stringify({scope:'clarify',exerciseId:null,solutionRequest:false}),safe,JSON.stringify(pass)]);const r=await h.run({lessonId:'variables',message});assert.equal(r.text,safe);assert.equal(r.approved,true);assert.equal(h.calls.length,3);assert.ok(h.calls[1].messages.some(m=>m.role==='system'&&m.content===CLARIFY_HINT));}});
test('fallback names the lesson concepts instead of asking what was tried',()=>{const text=buildFallback(curriculum.variables);assert.ok(text.includes('Переменные'));assert.ok(text.includes('int'));assert.ok(!/что ты (уже )?пробовал|переформулир/i.test(text));assert.ok(text.length>80);});
test('failed review of the repair cannot expose either draft',async()=>{const rejected='Перенеси объявление счётчика за пределы функции.';const h=harness([inside,rejected,JSON.stringify({...pass,approve:false,noSolution:false,reasonCodes:['solution']}),safe,new Error('review unavailable')]);const result=await h.run({lessonId:'variables',message:'реши'});assert.equal(result.kind,'unavailable');assert.equal(result.approved,false);assert.notEqual(result.text,rejected);assert.notEqual(result.text,safe);assert.equal(h.calls.length,5);});
test('code and raw markup never rendered',()=>{for(const text of ['```cpp\nint x=1;\n```','Вот исправление: int score = 10;','Подряд: Serial.println(10); delay(100);','<script>alert(1)</script>','Открой https://example.com','Ключ user_ABCDEFGHIJKLMNOPQRSTUVWXYZ'])assert.equal(textAllowed(text),false);assert.equal(textAllowed(safe),true);});
test('a single mention of a construct the child uses is still a valid hint',()=>{assert.equal(textAllowed('Нажатие читается через digitalRead(2); — сравни полученное значение с HIGH.'),true);assert.equal(textAllowed('Проверь, что в pinMode(2, INPUT); указан режим входа.'),true);});
test('invented task and malformed gate fail closed',async()=>{for(const value of ['not json',JSON.stringify({scope:'in',exerciseId:'task-forged',solutionRequest:false})]){const h=harness([value]);assert.equal((await h.run({lessonId:'variables',message:'вопрос'})).kind,'unavailable');assert.equal(h.calls.length,1);}});
test('turn cap keeps full bounded history',async()=>{const h=harness([]);assert.equal((await h.run({lessonId:'variables',message:'ещё',history:Array(24).fill({role:'user',content:'вопрос'})})).kind,'limit');assert.equal(h.calls.length,0);});
test('all stages receive shared foundations, while only reviewer receives exercise references',async()=>{const basicClarifications=[{title:'loop()',text:'FOUNDATION_SENTINEL'}];const calls=[];const sequence=[inside,safe,JSON.stringify(pass)];const run=createEngine({curriculum:{variables:{...curriculum.variables,basicClarifications}},callModel:async call=>{calls.push(call);return sequence.shift();}});const result=await run({lessonId:'variables',message:'А несколько лупов можно?',history:[{role:'user',content:'Про loop()'},{role:'assistant',content:OUTSIDE}]});assert.equal(result.approved,true);assert.equal(calls.length,3);for(const c of calls)assert.ok(JSON.stringify(c.messages).includes('FOUNDATION_SENTINEL'));assert.ok(!JSON.stringify(calls[0].messages).includes('PRIVATE_ANSWER_SENTINEL'));assert.ok(!JSON.stringify(calls[1].messages).includes('PRIVATE_ANSWER_SENTINEL'));assert.ok(JSON.stringify(calls[2].messages).includes('PRIVATE_ANSWER_SENTINEL'));});
test('exercise inferred from question reaches tutor and reviewer without client selection',async()=>{const h=harness([JSON.stringify({scope:'in',exerciseId:'task-1',solutionRequest:false}),safe,JSON.stringify(pass)]);const result=await h.run({lessonId:'variables',message:'Не растёт счётчик в задании'});assert.equal(result.approved,true);assert.ok(h.calls[0].messages[1].content.includes('"activeExerciseId":null'));for(const call of h.calls.slice(1))assert.ok(call.messages[1].content.includes('"activeExerciseId":"task-1"'));});
test('provider ignores reasoning and blocks key/truncated output',async()=>{const config={endpoint:'https://api.commandcode.ai/provider/v1/chat/completions',apiKey:'PRIVATE_TEST_KEY',tutorModel:'test',reviewerModel:'test'};for(const [content,finish,reason] of [['normal','length',''],['PRIVATE_TEST_KEY','stop',''],['normal','stop','PRIVATE_REASONING']]){let request;const call=createProvider(config,{fetchImpl:async(url,init)=>{request=JSON.parse(init.body);return {ok:true,json:async()=>({choices:[{finish_reason:finish,message:{content,reasoning_content:reason}}]})};}});if(finish==='stop'&&content==='normal')assert.equal(await call({role:'tutor',messages:[]}),content);else await assert.rejects(()=>call({role:'tutor',messages:[]}));assert.equal(request.stream,false);}});
test('transient 5xx is retried once, 4xx and repeated failure are not',async()=>{const config={endpoint:'https://api.commandcode.ai/provider/v1/chat/completions',apiKey:'PRIVATE_TEST_KEY',tutorModel:'test',reviewerModel:'test'};
const ok=()=>({ok:true,json:async()=>({choices:[{finish_reason:'stop',message:{content:'Ответ'}}]})});
const bad=status=>({ok:false,status,body:{cancel:async()=>{}}});
let attempts=0,reserved=0;
const call=(responses)=>createProvider(config,{reserveCall:()=>{reserved++;},fetchImpl:async()=>{attempts++;return responses.shift();}})({role:'tutor',messages:[]});
attempts=0;reserved=0;assert.equal(await call([bad(503),ok()]),'Ответ');assert.equal(attempts,2);assert.equal(reserved,1);
attempts=0;await assert.rejects(()=>call([bad(401),ok()]));assert.equal(attempts,1);
attempts=0;await assert.rejects(()=>call([bad(500),bad(520)]));assert.equal(attempts,2);});
test('credential leak and daily quota still fail closed',async()=>{const config={endpoint:'https://api.commandcode.ai/provider/v1/chat/completions',apiKey:'PRIVATE_TEST_KEY',tutorModel:'test',reviewerModel:'test'};const call=createProvider(config,{reserveCall:()=>{throw Error('Daily limit');},fetchImpl:async()=>({ok:true,json:async()=>({choices:[{finish_reason:'stop',message:{content:'PRIVATE_TEST_KEY'}}]})})});await assert.rejects(()=>call({role:'tutor',messages:[]}),/Daily limit/);});
