import http from 'node:http';import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import {createTutorServer} from '../server/server.mjs';
const root=path.resolve('output/ai-tutor/test-static');fs.mkdirSync(root,{recursive:true});fs.writeFileSync(path.join(root,'index.html'),'<h1>Preview</h1>');
const curriculum={one:{id:'one',title:'Урок 1',exercises:[{id:'task-1',title:'Задание',task:'Условие',reference:'PRIVATE_REFERENCE'}]},two:{id:'two',title:'Урок 2',exercises:[]}};
async function fixture(fn){let calls=[];const server=createTutorServer({staticRoot:root,curriculum,port:0,rateLimit:2,respond:async args=>{calls.push(args);return {text:'Объяснение по теме',kind:'answer',approved:true};}});await new Promise(r=>server.listen(0,'127.0.0.1',r));const url='http://127.0.0.1:'+server.address().port;const origin=url;
const fetcher=(route,opts={})=>fetch(url+route,{...opts,headers:{Host:new URL(url).host,...opts.headers}});
const first=await fetcher('/api/tutor/session?lesson=one');const session=await first.json();const cookie=first.headers.get('set-cookie').split(';')[0];const headers={Origin:origin,'Content-Type':'application/json','X-Tutor-CSRF':session.csrf,Cookie:cookie};
try{await fn({fetcher,headers,session,calls,url});}finally{server.closeAllConnections();await new Promise(r=>server.close(r));}}
test('only static build served; no source/credentials/traversal',()=>fixture(async({fetcher})=>{assert.equal((await fetcher('/')).status,200);for(const p of ['/server/tutor/prompts.mjs','/.env','/.config/vibe-boards-tutor/credentials.json','/%2e%2e/%2e%2e/etc/passwd','/package.json'])assert.equal((await fetcher(p)).status,404);assert.equal((await fetcher('/api/tutor/session?lesson=nope')).status,404);}));
test('session response contains no reference answers',()=>fixture(async({session})=>{assert.ok(!JSON.stringify(session).includes('PRIVATE_REFERENCE'));}));
test('origin, csrf and host checked',()=>fixture(async({fetcher,headers,calls,url})=>{const body=JSON.stringify({lessonId:'one',message:'Что такое переменная?'});for(const extra of [{Origin:'https://evil.example'},{'X-Tutor-CSRF':'wrong'}])assert.equal((await fetcher('/api/tutor/chat',{method:'POST',headers:{...headers,...extra},body})).status,403);assert.equal(calls.length,0);const code=await new Promise((resolve,reject)=>{const req=http.get(url+'/api/tutor/session?lesson=one',{headers:{Host:'evil.example'}},res=>{res.resume();resolve(res.statusCode);});req.on('error',reject);});assert.equal(code,403);}));
test('client cannot forge role, history, model, lesson or task',()=>fixture(async({fetcher,headers,calls})=>{for(const body of [{lessonId:'missing',message:'x'},{lessonId:'one',message:'x',history:[]},{lessonId:'one',message:'x',model:'other'},{lessonId:'one',message:'x',role:'system'},{lessonId:'one',message:'x',exerciseId:'fake'},{lessonId:'one',message:'x'.repeat(2001)}])assert.equal((await fetcher('/api/tutor/chat',{method:'POST',headers,body:JSON.stringify(body)})).status,400);assert.equal(calls.length,0);}));
test('server histories isolated by lesson; rate limiting',()=>fixture(async({fetcher,headers,calls})=>{const post=lessonId=>fetcher('/api/tutor/chat',{method:'POST',headers,body:JSON.stringify({lessonId,message:'Объясни тему'})});assert.equal((await post('one')).status,200);assert.equal((await post('two')).status,200);assert.deepEqual(calls[1].history,[]);const restored=await (await fetcher('/api/tutor/session?lesson=one',{headers:{Cookie:headers.Cookie}})).json();assert.equal(restored.history.length,2);assert.equal((await post('one')).status,429);}));
test('production behind TLS proxy: fixed origin, Secure cookie, API only, no forwarded-host trust',async()=>{
 const publicOrigin='https://vibe-boards.mooo.com';let calls=0;const server=createTutorServer({curriculum,port:0,apiOnly:true,publicOrigin,respond:async()=>{calls++;return {text:'Проверенный ответ',kind:'answer',approved:true};}});await new Promise(r=>server.listen(0,'127.0.0.1',r));
 const request=(route,{headers={},body}={})=>new Promise((resolve,reject)=>{const req=http.request({hostname:'127.0.0.1',port:server.address().port,path:route,method:body?'POST':'GET',headers:{Host:new URL(publicOrigin).host,...headers}},res=>{let raw='';res.on('data',x=>raw+=x);res.on('end',()=>resolve({status:res.statusCode,headers:res.headers,body:JSON.parse(raw)}));});req.on('error',reject);req.end(body);});
 try{const first=await request('/api/tutor/session?lesson=one');assert.equal(first.status,200);assert.match(first.headers['set-cookie'][0],/; Secure/);const headers={Origin:publicOrigin,'Content-Type':'application/json',Cookie:first.headers['set-cookie'][0].split(';')[0],'X-Tutor-CSRF':first.body.csrf};const body=JSON.stringify({lessonId:'one',message:'Объясни тему'});assert.equal((await request('/api/tutor/chat',{headers,body})).status,200);assert.equal(calls,1);assert.equal((await request('/api/tutor/chat',{headers:{...headers,Origin:'http://vibe-boards.mooo.com','X-Forwarded-Proto':'https'},body})).status,403);assert.equal((await request('/api/tutor/health',{headers:{Host:'evil.example','X-Forwarded-Host':new URL(publicOrigin).host}})).status,403);assert.equal((await request('/')).status,404);assert.equal((await request('/server/tutor/provider.mjs')).status,404);assert.equal((await request('/api/tutor/health')).body.ok,true);}finally{server.closeAllConnections();await new Promise(r=>server.close(r));}
});
